variable "region" {}
variable "project_name" {}
variable "vpc_cidr" {}
variable "public1_subnet_cidr" {}
variable "public2_subnet_cidr" {}
variable "app1_subnet_cidr" {}
variable "app2_subnet_cidr" {}
variable "data1_subnet_cidr" {}
variable "data2_subnet_cidr" {}